# Generated by Django 5.0 on 2023-12-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontent',
            name='extracted_keyword',
        ),
    ]
