# Generated by Django 5.0 on 2023-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imagecontent_extracted_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
