# Generated by Django 5.0 on 2023-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagecontent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcontent',
            old_name='decription',
            new_name='description',
        ),
    ]
